language: cpp
dist: trusty
compiler:
  - gcc

install:
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      sudo bash .travis/install_intel_opencl.sh;
    fi;

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RELWITHDEBINFO ..
  - make -j4
  - ./aplusb
  - ./bitonic
  - ./radix
